version: '2'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - ./mongodb-data/:/data/db

# docker-compose up
# docker start server-mongodb-1